# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

jobs:
- job: Consolidate_Artifacts
  continueOnError: false
  pool:
    name: Analog-1ES-WindowsLatest
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      targetPath: '$(Pipeline.Workspace)\BuildArtifacts'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Consolidated Build Artifacts'
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\BuildArtifacts'
      ArtifactName: 'BuildArtifacts'

- job: CodeSign_Binaries
  condition: and(succeeded(), or(eq(variables['SignBinaries'], 'true'), eq(variables['Build.SourceBranchName'], variables['SigningBranch'])))
  dependsOn: Consolidate_Artifacts
  continueOnError: false
  pool:
    name: Analog-1ES-WindowsLatest
  displayName: Signing Binaries
  steps:
  - script: echo Syncing Source
  - checkout: self
    submodules: true
  - script: echo Downloading Pipeline Artifacts
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: 'BuildArtifacts'
      buildType: 'current'
      targetPath: '$(Pipeline.Workspace)\BuildArtifacts'
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
  - task: UseDotNet@2
    displayName: 'Ensure .NET Core is present for ESRP code signing'
    inputs:
      packageType: 'sdk'
      version: 2.1.x
  - task: EsrpCodeSigning@1
    displayName: 'CodeSign Binaries'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      ConnectedServiceName: $(ESRPConnection)
      FolderPath: '$(Pipeline.Workspace)\BuildArtifacts'
      Pattern: 'AudioPluginMicrosoftSpatializerCrossPlatform.dll'
      SessionTimeout: 360
      MaxConcurrency: 5
      MaxRetryAttempts: 5
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode" : "CP-230012",
            "OperationCode" : "SigntoolSign",
            "Parameters" : {
              "OpusName" : "Microsoft",
              "OpusInfo" : "http://www.microsoft.com",
              "FileDigest" : "/fd \"SHA256\"",
              "PageHash" : "/NPH",
              "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          },
          {
            "KeyCode" : "CP-230012",
            "OperationCode" : "SigntoolVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          }
        ]
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Consolidated and Signed Artifacts'
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\BuildArtifacts'
      ArtifactName: 'BuildArtifacts'
